name: Release to eks DEV

on:
  push:
    branches: [ "development" ]

jobs:
  deploy_to_eks:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      id: install
        
    - name: Configure AWS credentials 
      uses: aws-actions/configure-aws-credentials@v1        
      with:                                                    
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_EKS }}       
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_EKS }}
        aws-region: eu-west-1

    - name: Login to Amazon ECR 
      id: login-ecr                        
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push docker image
      run: |
        docker build --file ./src/Presentation/Dockerfile -t currencyconverter-api-dev .
        docker tag currencyconverter-api-dev:latest 000000000000.dkr.ecr.eu-west-1.amazonaws.com/currencyconverter-api-dev:latest
        docker push 000000000000.dkr.ecr.eu-west-1.amazonaws.com/currencyconverter-api-dev:latest

    - name: Update kube config
      run: aws eks update-kubeconfig --name kepler-cluster
    
    - name: Retarts deployment
      run: kubectl rollout restart deployment  kepler-api-deployment-dev -n currencyconverter-dev